name: connect_four
description: Connect Four

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  logging: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/music/
